name: sleep-most
api-version: 1.13
version: "5.7"
main: me.mrgeneralq.sleepmost.Sleepmost
authors: [MrGeneralQ, LesleyXYZ, HorrendousEntity]
folia-supported: true
commands:
  sleepmost:
    usage: /sleepmost
    description: open the sleepmost help menu
    aliases: [sm]
softdepend: [PlaceholderAPI, GSit, SuperVanish, PremiumVanish, Essentials]