name: sleep-most
api-version: 1.13
version: ${project.version}
main: me.mrgeneralq.sleepmost.Sleepmost
authors: [MrGeneralQ, PandaCrafter1, HorrendousEntity]
commands:
  sleepmost:
    usage: /sleepmost
    description: open the sleepmost help menu
    aliases: [sm]
  sleep:
    usage: /sleep
    description: Allows players to register themselves as sleeping
softdepend: [PlaceholderAPI]
