name: sleep-most
api-version: 1.13
version: 4.6.3
main: me.mrgeneralq.sleepmost.Sleepmost
authors: [MrGeneralQ, PandaCrafter1, HorrendousEntity]
commands:
  sleepmost:
    usage: /sleepmost
    description: open the sleepmost help menu
    aliases: [sm]
softdepend:
  - PlaceholderAPI
