name: sleep-most
api-version: 1.13
version: 4.6.2
main: me.mrgeneralq.sleepmost.Sleepmost
authors: [MrGeneralQ, HorrendousEntity]
commands:
  sleepmost:
    usage: /sleepmost
    description: open the sleepmost help menu
    aliases: [sm]
