name: sleep-most
version: 4.6.0
api-version: 1.16
main: me.mrgeneralq.sleepmost.Sleepmost
authors: [MrGeneralQ, HorrendousEntity]
commands:
  sleepmost:
    usage: /sleepmost
    description: open the sleepmost help menu
    aliases: [sm]
