sleep:
  percentage-required: 50
  
  // prevents mob from targetting and attacking you
  mob-no-target: true

  
messages:
  prefix: '&f[&csleep-most&f]'
  night-skipped: '&bThe night was skipped!'
  players-left: '&bSleeping to skip night &f[&c%sleeping%/%required%&f]&b!'