sleep:
  percentage-required: 50
  mob-no-target: true

  
messages:
  prefix: '&f[&csleep-most&f]'
  night-skipped: '&bThe night was skipped!'
  players-left: '&6%player% &bwent to sleep! &f[&c%sleeping%/%required%&f]&b!'