sleep:
  percentage-required: 50
  mob-no-target: true

  
messages:
  prefix: '&f[&csleep-most&f]'
  night-skipped: '&bThe night was skipped!'
  storm-skipped: '&bThe storm was skipped!'
  players-left-night: '&bSleeping to skip night &f[&c%sleeping%/%required%&f]&b!'
  players-left-storm: '&bSleeping to skip the storm &f[&c%sleeping%/%required%&f]&b!'